rest:
    resource: "@RestBundle/Controller/"
    type:     annotation
    prefix:   /api/v1

error:
    path: /api/v1/{path}
    defaults: { _controller: RestBundle:Rest:error, path: "" }
    requirements:
        path: .*